// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversityAPI.Data;

#nullable disable

namespace UniversityAPI.Migrations
{
    [DbContext(typeof(UniDbContext))]
    [Migration("20251106192825_Fixed Price of living in dorm")]
    partial class FixedPriceoflivingindorm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniversityAPI.Models.Domain.Dorm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<Guid>("DormTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceOfLiving")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DormTypeId");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.HasIndex("UniversityId");

                    b.ToTable("Dorms");
                });

            modelBuilder.Entity("UniversityAPI.Models.Domain.DormType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DormTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d7ed0fe-900f-4780-80e6-12fd2f0ec4a4"),
                            TypeName = "corridor"
                        },
                        new
                        {
                            Id = new Guid("c0281486-d9ec-4bf8-8164-3cce39241d0a"),
                            TypeName = "block"
                        });
                });

            modelBuilder.Entity("UniversityAPI.Models.Domain.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("UniversityAPI.Models.Domain.University", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("UniversityAPI.Models.Domain.UniversityBuilding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.HasIndex("UniversityId");

                    b.ToTable("UniversityBuildings");
                });

            modelBuilder.Entity("UniversityAPI.Models.Domain.Dorm", b =>
                {
                    b.HasOne("UniversityAPI.Models.Domain.DormType", "DormType")
                        .WithMany("Dorms")
                        .HasForeignKey("DormTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityAPI.Models.Domain.Location", "Location")
                        .WithOne("Dorm")
                        .HasForeignKey("UniversityAPI.Models.Domain.Dorm", "LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityAPI.Models.Domain.University", "University")
                        .WithMany("Dorms")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DormType");

                    b.Navigation("Location");

                    b.Navigation("University");
                });

            modelBuilder.Entity("UniversityAPI.Models.Domain.University", b =>
                {
                    b.HasOne("UniversityAPI.Models.Domain.Location", "Location")
                        .WithOne("University")
                        .HasForeignKey("UniversityAPI.Models.Domain.University", "LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("UniversityAPI.Models.Domain.UniversityBuilding", b =>
                {
                    b.HasOne("UniversityAPI.Models.Domain.Location", "Location")
                        .WithOne("UniversityBuilding")
                        .HasForeignKey("UniversityAPI.Models.Domain.UniversityBuilding", "LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityAPI.Models.Domain.University", "University")
                        .WithMany("UniversityBuildings")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("University");
                });

            modelBuilder.Entity("UniversityAPI.Models.Domain.DormType", b =>
                {
                    b.Navigation("Dorms");
                });

            modelBuilder.Entity("UniversityAPI.Models.Domain.Location", b =>
                {
                    b.Navigation("Dorm")
                        .IsRequired();

                    b.Navigation("University")
                        .IsRequired();

                    b.Navigation("UniversityBuilding")
                        .IsRequired();
                });

            modelBuilder.Entity("UniversityAPI.Models.Domain.University", b =>
                {
                    b.Navigation("Dorms");

                    b.Navigation("UniversityBuildings");
                });
#pragma warning restore 612, 618
        }
    }
}
